# Generated by Django 4.1.1 on 2022-09-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievement',
            table='achievement',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
        migrations.AlterModelTable(
            name='speciality',
            table='speciality',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='yearofadmission',
            table='year_of_admission',
        ),
    ]
