# Generated by Django 4.1.1 on 2022-09-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ('faculty',)},
        ),
    ]
