# Generated by Django 4.1.1 on 2022-09-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_alter_speciality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='achievement.student'),
        ),
    ]
